var stayWithMe = [
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 3}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 3}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 3}],
[{key: 'C', octave: '4', duration: 3}],
[{key: 'C', octave: '4', duration: 5}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 3}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 3}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 3}],
[{key: 'A', octave: '4', duration: 3}],
[{key: 'D', octave: '4', duration: 5}],
// [{key: 'E', octave: '4', duration: 2}],
// [{key: 'E', octave: '4', duration: 2}],
// [{key: 'E', octave: '4', duration: 2}],
];

var tempoMelody = [
250,
250,
500,
250,
250,
500,
250,
250,
500,
500,
1000,
250,
250,
500,
250,
250,
500,
250,
250,
500,
500,
1000,
]

var stayWithMeHarmony = [
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 2}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 2}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 2}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 2}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 2}],
[{key: 'C', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
[{key: 'E', octave: '4', duration: 2}],
[{key: 'A', octave: '4', duration: 2}],
[{key: 'D', octave: '4', duration: 2}],
// [{key: 'E', octave: '4', duration: 2}],
// [{key: 'E', octave: '4', duration: 2}],
// [{key: 'E', octave: '4', duration: 2}],
];
